FROM jupyter/pyspark-notebook
LABEL version="v1.0.0"
LABEL app="spark"
WORKDIR /home/jovyan/work/
COPY test.py .
CMD ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0", "test.py"]
