version: '3'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
  kafka:
      image: confluentinc/cp-kafka:7.5.2
      container_name: kafka
      hostname: kafka
      ports:
        - 9092:9092
      depends_on:
        - zoo1
      environment:
        - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_BROKER_ID=3
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  jyputer:
      image: jupyter/pyspark-notebook
      ports:
        - 8889:8888
        - 4040:4040
      depends_on:
        - kafka
